apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: library-app-monitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
   matchLabels:
     app: library-app

  namespaceSelector:
    matchNames:
      - default

  endpoints:
     - port: http
       path: /metrics
       interval: 5s
